# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 19521b52d9ef71667546aa27d8ff76c418e92a8768bad172c5fc3db1b287c8d63a6496af29108a69307eebb3dab7e0607216be12131aa60e2c98af9b9c917fe8

test:
  secret_key_base: c8f8cae529288b73c2c87bd8cdbdb9c419984bd35351154ecbecf02e32f4fc673c4b39416157bb51da396b7f78a308b5ec7b81a4f139e83a3ab152a0e81168ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
